#!/bin/bash

IMAGE_NAME=${IMAGE_NAME-jos/jenkins-candidate}

CIDFILE_DIR=$(mktemp -t jenkins_test_cidfiles -d)

function cleanup() {
  for cidfile in $CIDFILE_DIR/* ; do
    CONTAINER=$(cat $cidfile)
    echo "Stopping and removing container $CONTAINER..."
    docker stop $CONTAINER
    exit_status=$(docker inspect -f '{{.State.ExitCode}}' $CONTAINER)
    echo "Dumping logs for $CONTAINER"
    # Dump the logs always (jenkins returns 143 when killed), so we can
    # identify the failures in Jenkins
    [[ "${exit_status}" != "143" ]] && docker logs $CONTAINER
    docker rm $CONTAINER
    rm $cidfile
    echo "Done."
  done
  rmdir $CIDFILE_DIR
  # This fails because the volume contains files owned by the container uid, so we can't clean it up.
  #rm -rf $VOLUME
}
trap cleanup EXIT SIGINT

function get_cid() {
  local id="$1" ; shift || return 1
  echo $(cat "$CIDFILE_DIR/$id")
}

function get_container_ip() {
  local id="$1" ; shift
  docker inspect --format='{{.NetworkSettings.IPAddress}}' $(get_cid "$id")
}

test_connection() {
  set +e
  echo "Testing HTTP connection..."
  local max_attempts=10
  local sleep_time=6
  local attempt=1
  local result=1
  while [ $attempt -le $max_attempts ]; do
    echo "Sending GET request to http://${CONTAINER_IP}:8080/"
    response_code=$(curl -s -w %{http_code} -o /dev/null "http://${CONTAINER_IP}:8080/")
    status=$?
    if [ $status -eq 0 ]; then
      if [ $response_code -eq 200 ]; then
        result=0
        break
      fi
    fi
    attempt=$(( $attempt + 1 ))
    sleep $sleep_time
  done
  set -e
  return $result
}


function create_container() {
  local name=$1 ; shift
  cidfile="$CIDFILE_DIR/$name"
  # create container with a cidfile in a directory for cleanup
  docker run --name=$name --cidfile $cidfile -d -p 8080:8080 $IMAGE_NAME
  echo "Created container $(cat $cidfile)"
}

function delete_container() {
  CONTAINER=$(cat $cidfile)
  docker stop $CONTAINER
  docker rm $CONTAINER
  rm $cidfile  
}


function run_tests() {
  local name=$1 ; shift
  create_container $name
  CONTAINER_IP=127.0.0.1
  test_connection $name
  echo "Connection test is successfull."
}

run_tests jenkins_test
echo "TEST SUCCESS!"
